### ISSUE TITLE
Negative Impact Assessment Values

### ISSUE THREAD

**Issue by cagaua1977** [uslci-admin/private-uslci-content#8]
Hi! I downloaded the latest version of USLCI for OpenLCA as well as TRACI and I am getting negative impact assessment values. Any ideas on how to fix this?
Thanks!

**Comment by sarahcashmanz** [comment]
@cagaua1977
USER GETTING NEGATIVE FLOWS:
This issue (having to do with allocation factors in petroleum refining) was resolved with the corrections released as of the USLCI 2020 (Summer Quarter) version. If you use the latest version of USLCI from the Federal LCA Commons, you will also need methods adapted to the Federal Elementary Flow List (FEDEFL), to which the USLCI converted in 2019. The FEDEFL and the FEDEFL-adapted methods are available on the Federal LCA Commons for download and import, e.g., into your openLCA desktop application. Please see the USLCI GitHub Support Content ([https://github.com/uslci-admin/uslci-content/wiki]) and/or the NREL USLCI Quick Help YouTube video series ([https://www.youtube.com/playlist?list=PLmIn8Hncs7bFUOyXZNGXwG4LtdoTfLz6Q]) for details on USLCI Database versioning because if you do not correctly import the new USLCI version, you will not overwrite these old errors; also, these videos have tips on: using FEDEFL-adapted methods and running calculations on USLCI in openLCA.
If you are using the Nexus-paid-for version of USLCI, you can manually implement relevant corrections from the USLCI Change Log into the Nexus paid-for verison until the updates become available from GreenDelta: [https://github.com/uslci-admin/uslci-content/blob/dev/docs/release_info/change-log.md])

**Comment by Jdvillegas1** [comment]
I downloaded the latest JSOn files for the database together with the no flows traci file and I keep having those negative results

**Comment by Jdvillegas1** [comment]
> Hi! I downloaded the latest version of USLCI for OpenLCA as well as TRACI and I am getting negative impact assessment values. Any ideas on how to fix this? Thanks!

Was this solved for you?

**Comment by FLCAC-admin** [comment]
Hi @Jdvillegas1 apologies for not responding to this sooner! There could be a couple of solutions to this issue - the first is to ensure that you are importing USLCI into your OpenLCA database before importing the no flows version of TRACI. The second is to make sure that an allocation method is chosen when calculating results (see attached screenshot), if the allocation method is set to "None" then results are often negative. Please let me know if these solution don't solve the issue.

![image](https://github.com/uslci-admin/uslci-content/assets/30633509/4a9e8ddd-d304-42c0-bfef-1dbd2c704f23)

**Comment by Jdvillegas1** [comment]
Thank you so much,

The allocation parameter solved the problem!


Juan David Villegas 
VICE PRESIDENT, SUSTAINABILITY ADVISORY, GLOBAL MARKETS

BMO RADICLE  |  BALANCE IS POSSIBLE
SUITE #1930, 401-9 AVENUE SW, CALGARY AB T2P 3C5
RADICLEBALANCE.COM

DISCLAIMER: This email and its attachments are confidential. Any unauthorized use or disclosure is prohibited.
​If you receive this email in error, ​please notify me by reply email and permanently delete the original without
​making any copies or disclosing its contents. BMO Radicle is a brand name for the sustainability advisory services
​and solutions of BMO Financial Group. BMO Financial Group is a brand name representing Bank of Montreal and 
​its subsidiaries and affiliates. 
Please consider the environment before printing this email.
From: uslci-admin ***@***.***>
Sent: Wednesday, October 4, 2023 6:45 PM
To: uslci-admin/uslci-content ***@***.***>
Cc: Juan David Villegas ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [uslci-admin/uslci-content] Negative Impact Assessment Values (Issue #8)


Hi @Jdvillegas1<https://urldefense.com/v3/__https://github.com/Jdvillegas1__;!!O9lNpA!jWpj0xbANAUgbLmw9VT9V4cpXjiircbZWlcNlWstP7-C40SpCkA_enF0Dcx69qSSJa8VWcxbmYADDA7DI6R_zvZ_SpGjax0$> apologies for not responding to this sooner! There could be a couple of solutions to this issue - the first is to ensure that you are importing USLCI into your OpenLCA database before importing the no flows version of TRACI. The second is to make sure that an allocation method is chosen when calculating results (see attached screenshot), if the allocation method is set to "None" then results are often negative. Please let me know if these solution don't solve the issue.

[image]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/30633509/272729096-4a9e8ddd-d304-42c0-bfef-1dbd2c704f23.png__;!!O9lNpA!jWpj0xbANAUgbLmw9VT9V4cpXjiircbZWlcNlWstP7-C40SpCkA_enF0Dcx69qSSJa8VWcxbmYADDA7DI6R_zvZ_ePnf36Q$>

-
