### ISSUE TITLE
Issues implementing US LCI with Brightway2

### ISSUE THREAD

**Issue by macmribo** [uslci-admin/private-uslci-content#9]
Hello! I work for NREL and I am trying to import the US LCI database to the open source LCA tool Brightway2. The program needs EcoSpold version for it to work, so I used the latest [EcoSpold](https://github.com/uslci-admin/uslci-content/blob/dev/downloads/uslci_fy21_q3_01_olca_10_3_ecospold2.zip) version. 

Investigating the EcoSpold file, it seems that the conversion lost the 'Energy, at grid' specific details in the name. For example, 'Electricity, at Grid, SPP, 2010 - RNA' appears as 'Electricity, at grid' in the .xml file. Is this an OpenLCA error? Is there a way to circumvent this? 

As said in the documentation, I am aware of the OpenLCA data loss, however, this format change seems pretty specific only for the 22: Utilities, 2211: Electric Power Generation, Transmission and Distribution 'Electricity, at grid' so there might be a way to fix this?

I know this is a very long question, I would appreciate a person of contact to maybe set up a meeting and check my options to implement USLCI into Brightway2.

Thank you!

**Comment by robinsonkwame** [comment]
@uslci-admin

**Comment by FLCAC-admin** [comment]
Apologies for the delayed response on this post. Within USLCI it is possible to have one flow that can be produced by multiple processes. In OpenLCA, a flow can be linked to a desired process by selecting the process in the provider field (e.g., flow: 'Electricity, at grid RNA' and provider: 'Electricity, at Grid, SPP, 2010 - RNA'). 

The name in the xml file for each process refers to the flow name, rather than the process name. The process is indicated by the UUID in the title of the xml file. I believe that this is the reason that you are seeing 'Electricity, at grid' instead of the name of the process producing that flow - 'Electricity, at Grid, SPP, 2010 - RNA'. The metadata and inventory in the xml file refer to the process producing the flow. Unfortunately, the lack of a process name in the xml file is a limitation of the EcoSpold file format. You may find this page helpful: http://greendelta.github.io/olca-schema/#why-another-lca-data-exchange-format.

Please let us know if you'd like to discuss this further with us. You can also contact us at USLCI@erg.com.
